const express = require('express');
const router = express.Router();

const Controller = require('../Controller/SalesController')

router.get('/total-revenue',Controller.total_revenue);
router.get('/quantity-by-product',Controller.quantity_by_product);
router.get('/top-products',Controller.top_products);
router.get('/average-price',Controller.average_price);
router.get('/revenue-by-month',Controller.revenue_by_month);
router.get('/highest-quantity-sold',Controller.highest_quantity_sold);





module.exports = router;


// GET /api/sales/total-revenue: Calculate and return the total revenue generated by all sales transactions.
// GET /api/sales/quantity-by-product: Find and return the total quantity sold for each product.
// GET /api/sales/top-products: Retrieve the top 5 products with the highest total revenue, along with their total revenue values.
// GET /api/sales/average-price: Calculate and return the average price of products sold.
// GET /api/sales/revenue-by-month: Group the sales data by month and year and calculate the total revenue for each month-year combination.
// GET /api/sales/highest-quantity-sold: Find and return the product that had the highest quantity sold on a single day.